# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\"o\n\x11\x43reateUserRequest\x12\x0e\n\x06\x66_name\x18\x01 \x01(\t\x12\x0e\n\x06l_name\x18\x02 \x01(\t\x12\x0b\n\x03\x64ob\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\"\xa2\x01\n\x12\x43reateUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12,\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x1b.CreateUserResponse.Details\x12\x19\n\x11generated_user_id\x18\x03 \x01(\t\x12\x17\n\x0finitial_balance\x18\x04 \x01(\x01\x1a\x1a\n\x07\x44\x65tails\x12\x0f\n\x07message\x18\x01 \x01(\t\"z\n\x0e\x44\x65positRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65posit_method\x18\x04 \x01(\t\x12\x1d\n\x15transaction_reference\x18\x05 \x01(\t\"\xb8\x01\n\x0f\x44\x65positResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x15.DepositResponse.Data\x1a_\n\x04\x44\x61ta\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65posit_method\x18\x02 \x01(\t\x12\x1d\n\x15transaction_reference\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"$\n\x11GetBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x99\x01\n\x12GetBalanceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x18.GetBalanceResponse.Data\x1a:\n\x04\x44\x61ta\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t2\xaf\x01\n\x0b\x42\x61nkService\x12\x35\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12\x32\n\rDepositAmount\x12\x0f.DepositRequest\x1a\x10.DepositResponse\x12\x35\n\nGetBalance\x12\x12.GetBalanceRequest\x1a\x13.GetBalanceResponseb\x06proto3')



_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_CREATEUSERRESPONSE = DESCRIPTOR.message_types_by_name['CreateUserResponse']
_CREATEUSERRESPONSE_DETAILS = _CREATEUSERRESPONSE.nested_types_by_name['Details']
_DEPOSITREQUEST = DESCRIPTOR.message_types_by_name['DepositRequest']
_DEPOSITRESPONSE = DESCRIPTOR.message_types_by_name['DepositResponse']
_DEPOSITRESPONSE_DATA = _DEPOSITRESPONSE.nested_types_by_name['Data']
_GETBALANCEREQUEST = DESCRIPTOR.message_types_by_name['GetBalanceRequest']
_GETBALANCERESPONSE = DESCRIPTOR.message_types_by_name['GetBalanceResponse']
_GETBALANCERESPONSE_DATA = _GETBALANCERESPONSE.nested_types_by_name['Data']
CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), {

  'Details' : _reflection.GeneratedProtocolMessageType('Details', (_message.Message,), {
    'DESCRIPTOR' : _CREATEUSERRESPONSE_DETAILS,
    '__module__' : 'bank_pb2'
    # @@protoc_insertion_point(class_scope:CreateUserResponse.Details)
    })
  ,
  'DESCRIPTOR' : _CREATEUSERRESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserResponse)
  })
_sym_db.RegisterMessage(CreateUserResponse)
_sym_db.RegisterMessage(CreateUserResponse.Details)

DepositRequest = _reflection.GeneratedProtocolMessageType('DepositRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:DepositRequest)
  })
_sym_db.RegisterMessage(DepositRequest)

DepositResponse = _reflection.GeneratedProtocolMessageType('DepositResponse', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _DEPOSITRESPONSE_DATA,
    '__module__' : 'bank_pb2'
    # @@protoc_insertion_point(class_scope:DepositResponse.Data)
    })
  ,
  'DESCRIPTOR' : _DEPOSITRESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:DepositResponse)
  })
_sym_db.RegisterMessage(DepositResponse)
_sym_db.RegisterMessage(DepositResponse.Data)

GetBalanceRequest = _reflection.GeneratedProtocolMessageType('GetBalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBALANCEREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:GetBalanceRequest)
  })
_sym_db.RegisterMessage(GetBalanceRequest)

GetBalanceResponse = _reflection.GeneratedProtocolMessageType('GetBalanceResponse', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _GETBALANCERESPONSE_DATA,
    '__module__' : 'bank_pb2'
    # @@protoc_insertion_point(class_scope:GetBalanceResponse.Data)
    })
  ,
  'DESCRIPTOR' : _GETBALANCERESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:GetBalanceResponse)
  })
_sym_db.RegisterMessage(GetBalanceResponse)
_sym_db.RegisterMessage(GetBalanceResponse.Data)

_BANKSERVICE = DESCRIPTOR.services_by_name['BankService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEUSERREQUEST._serialized_start=14
  _CREATEUSERREQUEST._serialized_end=125
  _CREATEUSERRESPONSE._serialized_start=128
  _CREATEUSERRESPONSE._serialized_end=290
  _CREATEUSERRESPONSE_DETAILS._serialized_start=264
  _CREATEUSERRESPONSE_DETAILS._serialized_end=290
  _DEPOSITREQUEST._serialized_start=292
  _DEPOSITREQUEST._serialized_end=414
  _DEPOSITRESPONSE._serialized_start=417
  _DEPOSITRESPONSE._serialized_end=601
  _DEPOSITRESPONSE_DATA._serialized_start=506
  _DEPOSITRESPONSE_DATA._serialized_end=601
  _GETBALANCEREQUEST._serialized_start=603
  _GETBALANCEREQUEST._serialized_end=639
  _GETBALANCERESPONSE._serialized_start=642
  _GETBALANCERESPONSE._serialized_end=795
  _GETBALANCERESPONSE_DATA._serialized_start=737
  _GETBALANCERESPONSE_DATA._serialized_end=795
  _BANKSERVICE._serialized_start=798
  _BANKSERVICE._serialized_end=973
# @@protoc_insertion_point(module_scope)
